import React, { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, IconButton, Pagination, TextField } from '../components/Inputs'
import { useAppContext } from '../modules/dashboard/Provider'
import styles from '../styles/Home.module.css'
import { Select } from '../components/Inputs/Select'
import Link from 'next/link'

const Home: NextPage = () => {
  const { mountains, setSearch, setSort } = useAppContext()
  return (
    <div style={{ minHeight: 1282 }}>
      <Head>
        <title>Mountains</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inputContainer}>
        <div className={styles.searchContainer}>
          <TextField onChange={(e) => setSearch(e?.target?.value)} />
        </div>
        <div className={styles.sortContainer}>
          <Select
            options={[
              {
                label: 'A-Z',
                value: 'asc'
              },
              {
                label: 'Z-A',
                value: 'desc'
              }
            ]}
            onChange={(e) => setSort(e.target.value)}
          />
        </div>

      </div>
      <div className={styles.container}>
        {
          mountains?.map((mountain: any, key: number) => (
            <div
              style={{
                display: 'flex',
                flexDirection: 'column'
              }}
              key={key}
            >
              <div
                className={styles.backgroundImage}
                style={{
                  backgroundImage: `url("/${mountain.slug}.jpg")`,
                  objectFit: 'cover',
                  backgroundSize: '100% 100%',
                  backgroundRepeat: 'no-repeat',
                  borderRadius: '8px'
                }}
              >
                <Link href={`/mountains/${mountain.slug}`} passHref>
                  <IconButton />
                </Link>
              </div>
              <p>{mountain.title}</p>
              <p>{mountain.title_long}</p>
            </div>
          ))
        }
      </div>
      <div className={styles.buttonContainer}>
        <Pagination pageCount={9} />
        <Button label={'Show Next'} />
      </div>
    </div>
  )
}

export default Home
